#!/usr/bin/env python3

import argparse
import json
import glob
import sys

parser = argparse.ArgumentParser(description='')

parser.add_argument('directory',
                    help='The dependencies input file')
parser.add_argument('--include-node-modules', action='store_const',
                    const=True, default=False,
                    help='Include the dependencies in the installed /node_modules/ fodlders')
args = parser.parse_args()

def included(path):
    if args.include_node_modules:
        return True
    else:
        return "/node_modules/" not in path

for path in filter(included, glob.glob(args.directory + "/**/package.json", recursive=True)):
    with open(path) as package_file:
        package = json.load(package_file)
        package_name = package["name"] if "name" in package else "<<unnamed>>"
        print("'{}':".format(package_name))
        if "dependencies" in package:
            for key in package["dependencies"]:
                print(" - '{}'".format(key))
        print("")
